- name: Deploy common services
  hosts: all
  roles:
    - common
    - dnsmasq
    - ufw
    - fail2ban-endlessh

- name: Create encrypted folder
  hosts: encrypted_folder
  roles:
    - encrypted-folder

- name: Setup k0s
  hosts: k0s
  roles:
    - k0s/setup

- name: Configure k0s initial controller
  hosts: k0s_initial_controller
  roles:
    - k0s/initial_controller

- name: Configure k0s controllers
  hosts: k0s_controller
  roles:
    - k0s/controller

- name: Configure k0s worker
  hosts: k0s_worker
  roles:
    - k0s/worker