- hosts: all
  become: 'yes'
  remote_user: root
  vars:
    packages:
      - fish

  tasks:
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present

    - name: Create user account
      user:
        name: "{{ user }}"
        password: "{{ password | string | password_hash('sha512') }}"
        groups:
          - sudo
        shell: /usr/bin/fish
        state: present

    - name: Create the .ssh directory
      file:
        path: /home/{{ user }}/.ssh
        state: directory

    - name: Install SSH key
      get_url:
        url: https://akarys.me/ssh
        dest: /home/{{ user }}/.ssh/authorized_keys
        owner: root
        group: root

    - name: Install host file
      template:
        src: etc/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root

    - name: Set new hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Update sshd configuration
      ansible.builtin.template:
        src: etc/ssh/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'
        validate: /usr/sbin/sshd -t -f %s
        backup: yes

    - name: Reload SSHD
      shell: kill -HUP $(pgrep -f "sshd -D") & exit 0
