- name: Install PowerDNS
  apt:
    name:
      - pdns-server
      - pdns-backend-pgsql
      - postgresql-client
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: Allow TCP/53
  ufw:
    rule: allow
    proto: tcp
    port: 53

- name: Allow UDP/53
  ufw:
    rule: allow
    proto: udp
    port: 53

- name: Create database
  command: psql -U powerdns -h postgres.default.svc.cluster.local -d powerdns -a -f /usr/share/doc/pdns-backend-pgsql/schema.pgsql.sql
  environment:
    - PGPASSWORD: "{{ postgres_password }}"

- name: Create config file
  template:
    src: pdns.conf.j2
    dest: /etc/powerdns/pdns.conf
    owner: root
    group: root
    mode: 0644
  notify: restart powerdns

- name: Start and enable PowerDNS
  systemd:
    name: pdns
    state: started
    enabled: true
    daemon_reload: yes