- name: Install UFW
  apt:
    name:
      - ufw
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: Allow TCP/22
  ufw:
    rule: allow
    proto: tcp
    port: 22

- name: Allow 127.0.0.1
  ufw:
    rule: allow
    proto: tcp
    from: 127.0.0.1

- name: Enable UFW
  ufw:
    state: enabled
    policy: reject

- name: Start and enable ufw
  systemd:
    name: ufw
    state: started
    enabled: true
    daemon_reload: yes