- name: Install DNSMasq
  apt:
    name:
      - dnsmasq
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: Make DNSMasq bind only to localhost
  template:
    src: dnsmasq.d/bind-to-lo.conf.j2
    dest: /etc/dnsmasq.d/bind-to-lo.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq

- name: Add CoreDNS (kuber-dns) config
  template:
    src: dnsmasq.d/kube-dns.conf.j2
    dest: /etc/dnsmasq.d/kube-dns.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
  when: "'k0s' in groups"

- name: Start and enable dnsmasq
  systemd:
    name: dnsmasq
    state: started
    enabled: true
    daemon_reload: yes

- name: Update resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq